-- MySQL Script generated by MySQL Workbench
-- Fri Mar 13 17:10:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chatbot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chatbot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chatbot` DEFAULT CHARACTER SET utf8 ;
USE `chatbot` ;

-- -----------------------------------------------------
-- Table `chatbot`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(45) NOT NULL UNIQUE,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatbot`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot`.`documento` (
  `iddocumento` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `linguagem` VARCHAR(45) NOT NULL,
  `conteudo` LONGTEXT NOT NULL,
  `data_att` DATE NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`iddocumento`),
  INDEX `fk_documento_usuario_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_documento_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `chatbot`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatbot`.`chunk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot`.`chunk` (
  `idchunk` INT NOT NULL AUTO_INCREMENT,

  `tipo` ENUM(
    'include',
    'namespace',
    'class',
    'struct',
    'enum',
    'function',
    'method',
    'constructor',
    'destructor',
    'macro',
    'typedef',
    'global_variable',
    'comment',
    'other'
  ) NOT NULL DEFAULT 'other',

  `conteudo` LONGTEXT NOT NULL,

  `linha_ini` INT NOT NULL,
  `linha_fim` INT NOT NULL,

  `iddocumento` INT NOT NULL,

  PRIMARY KEY (`idchunk`),

  INDEX `idx_chunk_tipo` (`tipo`),
  INDEX `idx_chunk_linhas` (`linha_ini`, `linha_fim`),

  INDEX `fk_chunk_documento1_idx` (`iddocumento` ASC) VISIBLE,

  CONSTRAINT `fk_chunk_documento1`
    FOREIGN KEY (`iddocumento`)
    REFERENCES `chatbot`.`documento` (`iddocumento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE

) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `chatbot`.`conversa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot`.`conversa` (
  `idconversa` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `data_criacao` DATE NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idconversa`),
  INDEX `fk_conversa_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_conversa_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `chatbot`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatbot`.`mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot`.`mensagem` (
  `idmensagem` INT NOT NULL AUTO_INCREMENT,
  `conteudo` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `idconversa` INT NOT NULL,
  PRIMARY KEY (`idmensagem`),
  INDEX `fk_mensagem_conversa1_idx` (`idconversa` ASC) VISIBLE,
  CONSTRAINT `fk_mensagem_conversa1`
    FOREIGN KEY (`idconversa`)
    REFERENCES `chatbot`.`conversa` (`idconversa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatbot`.`mensagem_processada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot`.`mensagem_processada` (
  `idmensagem_processada` INT NOT NULL AUTO_INCREMENT,
  `conteudo` VARCHAR(45) NOT NULL,
  `tempo` INT NOT NULL,
  `intencao` VARCHAR(45) NOT NULL,
  `entidades` VARCHAR(45) NOT NULL,
  `idmensagem` INT NOT NULL,
  PRIMARY KEY (`idmensagem_processada`),
  INDEX `fk_mensagem_processada_mensagem1_idx` (`idmensagem` ASC) VISIBLE,
  CONSTRAINT `fk_mensagem_processada_mensagem1`
    FOREIGN KEY (`idmensagem`)
    REFERENCES `chatbot`.`mensagem` (`idmensagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatbot`.`resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot`.`resposta` (
  `idresposta` INT NOT NULL AUTO_INCREMENT,
  `conteudo` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `avaliacao` INT NULL,
  `idmensagem_processada` INT NOT NULL,
  PRIMARY KEY (`idresposta`),
  INDEX `fk_resposta_mensagem_processada1_idx` (`idmensagem_processada` ASC) VISIBLE,
  CONSTRAINT `fk_resposta_mensagem_processada1`
    FOREIGN KEY (`idmensagem_processada`)
    REFERENCES `chatbot`.`mensagem_processada` (`idmensagem_processada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatbot`.`chunk_has_resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot`.`chunk_has_resposta` (
  `idchunk` INT NOT NULL,
  `idresposta` INT NOT NULL,
  PRIMARY KEY (`idchunk`, `idresposta`),
  INDEX `fk_chunk_has_resposta_resposta1_idx` (`idresposta` ASC) VISIBLE,
  INDEX `fk_chunk_has_resposta_chunk1_idx` (`idchunk` ASC) VISIBLE,
  CONSTRAINT `fk_chunk_has_resposta_chunk1`
    FOREIGN KEY (`idchunk`)
    REFERENCES `chatbot`.`chunk` (`idchunk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chunk_has_resposta_resposta1`
    FOREIGN KEY (`idresposta`)
    REFERENCES `chatbot`.`resposta` (`idresposta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
